openapi: 3.0.0
info:
  title: Sample API
  description: Esta es un API de prueba.
  version: 1.0.0
servers:
- url: http://localhost:3002
paths:
  /users/{id}:
    get:
      summary: Returns a user by ID
      parameters:
      - name: id
        in: path
        description: The ID of the user to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 10
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Cambio la descripción
        "404":
          description: A user with the specified ID was not found
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        id:
          type: integer
          example: 10
        name:
          type: string
          example: "Juan"
